[Acknowledgements]

== Acknowledgements 

=== Course design and instruction

The success of this course depends heavily on the support provided to participants from GBIF's network of capacity enhancement mentors. 
Visit the GBIF page on https://www.gbif.org/article/5SExsCfj7UaUkMCsuc6Oec/mentors-and-trainers[capacity enhancement mentoring^] to read more about these individuals and their contributions.

The following individuals are recognized for their significant contributions to the course design, materials and instruction:

* Nadine Bowles Newark
* Andrea Baquero
* Kate Ingenloff
* Hannah Owens
* Melianie Raymond
* Andrew Rodrigues
* Laura Anna Russell
* John Tayleur
* John Waller

Special acknowledgement ...

=== Translators

==== Spanish
* Anabela Plos
* Paula Zermoglio

==== French

* Patricia Mergen
* Anne Sophie Archambeau

=== Resources

* https://www.r-project.org/[R^]
* https://wallaceecomod.github.io/vignettes/wallace_vignette.html[Wallace Ecological Niche Modelling Vignette^]
* IUCN Red List of Threatened Species[https://www.iucnredlist.org/^]

