== Final assignments

[NOTE.assignments]
For your final activities, you will complete and submit ... for evaluation.

=== Assignment 1
There are ...

Required files for submission:

* completed exercise sheet (MS Word Doc or similar is acceptable)
* spreadsheet (MS Excel, csv, txt or similar is acceptable)
* dataset (MS Excel, csv, txt or similar is acceptable)

IMPORTANT: Include the assignment name and exercise number along with your name on all files submitted. For example, Russell-UC2-IS-exercise-sheet.docx, Russell-UC2-IS-2.xlsx, Russell-UC2-IS-3.xlsx. *All files must be submitted in English*. Contact training@gbif.org if you have any questions.

=== Assignment submission

// Create a Box submission form and replace with appropriate link

ifdef::backend-pdf[]
Assignments can be submitted from the online (HTML) version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
Please submit your assignment files using the form below.  If you do not see a form, you can also visit the https://gbif.app.box.com/f/1e44182c4bc74d659082c0e952d83e80:[submission site^] in a new window.

++++
<iframe src="https://gbif.app.box.com/f/1e44182c4bc74d659082c0e952d83e80" style="width: 100%; min-height: 900px;"></iframe>
++++
endif::backend-pdf[]
