[multipage-level=2]
== Section/chapter title 

Paragraph1, sentence1.
Sentence 2.
Sentence 3.

Paragraph2, sentence1.
Sentence 2.
Sentence 3.

Paragraph3, sentence1.
Sentence 2.
Sentence 3.

=== sub topic

[NOTE.presentation]
In this video (12:26), you will review ... used in this course. 
If you are unable to watch the embeded Vimeo video, you can download it locally. (MP4 - 44.5 MB)

video::FZAF5Sy8Nsc[youtube, height=540, width=960, align=center]

// Start embedded presentation

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSgzwh3c26F38-TtMNkjykJT_PI8uY4_5INkI9da6rZiDFLX6_c1TZmX26KesqzDA/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++
endif::backend-pdf[]

// End embedded presention

[NOTE.activity]
Become familiar with the ...

****
this is an example of a block
this second sentence

this is second paragraph first sentence.
this is second sentence
****

==== sub sub topic

Paragraph1, sentence1.
Sentence 2.
Sentence 3.

“Paragraph2, sentence1.
Sentence 2.
Sentence 3.
