[description]
== Description

****
This course enables participants to plan and implement biodiversity data mobilization efforts effectively using accepted community standards.
Its aim is to facilitate the use of GBIF-mediated data for a number of key use cases that feed into decision-making processes.
This course was first developed as part of the Biodiversity Information for Development (BID) programme funded by the European Union.

Topics include:

*	Data Processing
*	Ecological Niche Modelling
*	Red List Assessments

This course is comprised of online content paired with quizzes and practical exercises. When offered as an onsite or virtual workshop, group work and social interaction are encouraged.


Topics include:

* Fit-for-Purpose Data
** Processing a GBIF-mediated dataset and making it “fit-for-purpose”
* Data for Species Assessments
** Using GBIF-mediated data for creating species distribution maps using IUCN mapping standards 
** Using GBIF-mediated data for assessing species conservation status using the IUCN Red List Categories and Criteria 
* Ecological Niche Modelling
** Introduction to running and interpreting a basic ecological model to determine the distribution of a species
** Exploring niche modelling under different environmental conditions



This course is comprised of ... 
Second sentence...
****

=== Audience
This course is designed for individuals who work as researchers or technicians in biodiversity research or policy institutions.
The instruction provided is particularly useful for those who have a need or desire to use GBIF-mediated data in their own research or analyses.


=== Prerequisites

* Introduction to GBIF course

Additionally, to make best use of the activities around this course, the participants should possess the following skills and knowledge:

* Basic skills in computer and internet use, and, in particular, in the use of spreadsheets.
* Basic understanding of computer-based geographical and statistical analysis tools e.g. GIS and R, and may have already run analyses using these tools.
* Basic knowledge about geography and biodiversity informatics: geography and mapping concepts, basic taxonomy and nomenclature rules.
* Willingness to disseminate the knowledge learned in the workshop with partners and collaborators in your project by adapting the biodiversity data use training materials to specific contexts and languages while maintaining their instructional value.
* A good command of English. While efforts are made to provide materials in other languages, instruction/videos will be in English.



. prerequisite 1 if any

. prerequisite 2 if any

=== Learning objectives

* Understanding common data quality issues that may affect data use
* Apply data processing routines on GBIF downloads to create fit for purpose datasets
* Learn the difference between fundamental and realized niches
* Explain how to delimit a training region
* Generate a simple niche model
* Explain niche model results
* Identify areas of uncertainty in projection
* Develop a communication strategy and convincing arguments for the integration of biodiversity into decision making processes
* Apply criterion B of the IUCN Categories and Criteria for the assessment of a species conservation status using a fit-for purpose dataset
* Apply IUCN mapping protocols for the production of Red List species distribution maps


* Objective
* Objective
* Objective
* Objective

// inlude if needed, otherwise remove
=== Certification

Upon successful completion of the course and successful assessment of assignments (by trainers/mentors), participants have the opportunity to receive an official certification in the form of a Mozilla Open Badge.

Participants are required to submit ... and it is scored against the educational rubrics for the course. 

* An overall score of ??? earns a BASIC badge
* An overall score of ??? earns an ADVANCED badge
