[description]
== Description

****
This course takes a modular approach to training in the use of GBIF-mediated data and builds on the Data Use for Decision Making course.
Different use cases have been developed that will get you started on some of the many different ways you can use GIBF-mediated data.

This course is comprised of online content paired with quizzes and you should complete these first.  
You can then complete the relevant use case that will build on what you have learnt through a set of practical exercises. 
When offered as an onsite or virtual workshop, group work and social interaction are encouraged.

The course comprises of one compulsory course in Data Processing and then optional modules that you can follow based on the learning path that is most relevant to you. 
The first two optional modules that we have develpoed are:

*	Ecological Niche Modelling
*	Red List Assessments


Topics include:

* Fit-for-Purpose Data
** Processing a GBIF-mediated dataset and making it “fit-for-purpose”
* Ecological Niche Modelling
** Introduction to running and interpreting a basic ecological model to determine the distribution of a species
** Exploring niche modelling under different environmental conditions
* Data for Species Assessments
** Using GBIF-mediated data for creating species distribution maps using IUCN mapping standards 
** Using GBIF-mediated data for assessing species conservation status using the IUCN Red List Categories and Criteria 

****

=== Audience
This course is designed for individuals who work as researchers or technicians in biodiversity research or policy institutions.
The instruction provided is particularly useful for those who have a need or desire to use GBIF-mediated data in their own research or analyses.

=== Prerequisites

* Introduction to GBIF course

Additionally, to make best use of the activities around this course, the participants should possess the following skills and knowledge:

* Basic skills in computer and internet use, and, in particular, in the use of spreadsheets.
* Basic understanding of computer-based geographical and statistical analysis tools e.g. GIS and R, and may have already run analyses using these tools.
* Basic knowledge about geography and biodiversity informatics: geography and mapping concepts, basic taxonomy and nomenclature rules.
* Willingness to disseminate the knowledge learned in the workshop with partners and collaborators in your project by adapting the biodiversity data use training materials to specific contexts and languages while maintaining their instructional value.
* A good command of English. While efforts are made to provide materials in other languages, instruction/videos will be in English.

=== Learning objectives

* Understanding common data quality issues that may affect data use
* Apply data processing routines on GBIF downloads to create fit for purpose datasets
* Learn the difference between fundamental and realized niches
* Explain how to delimit a training region
* Generate a simple niche model
* Explain niche model results
* Identify areas of uncertainty in projection
* Develop a communication strategy and convincing arguments for the integration of biodiversity into decision making processes
* Apply criterion B of the IUCN Categories and Criteria for the assessment of a species conservation status using a fit-for purpose dataset
* Apply IUCN mapping protocols for the production of Red List species distribution maps

=== Certification
Certificates in the form of digital badges will be issued to participants that successfuly complete a use case assignment.  There are several use cases and you should complete the ones that are of most relevance to your work or that interest you.  


