[description]
== Description

****
This workshop working in collaboration with UNEP-WCMC’s CONNECT programme aims to demonstrate how mobilized primary biodiversity data can be integrated into national policy-making processes. 
Participants will be introduced to the importance of biodiversity data within the decision making process before learning how to clean data and running key analyses - determining the distribution of a species and assessing the conservation status of species.  
Participants will then learn how to communicate their results to key stakeholders in the decision making process.

The event will have online and onsite components and both will have a strong practical approach (including a significant component of group work). 
Participants will have the possibility to evaluate their learning and receive recognition of their level of understanding with a digital badge . 
The official language of the workshop will be English.

Only participants and mentors who have been selected by the GBIF Secretariat can subscribe to this workshop. Please address any questions you may have with respect to the course to Andrew Rodrigues arodrigues@gbif.org.

Topics include:

* Fit-for-Purpose Data
** Processing a GBIF-mediated dataset and making it “fit-for-purpose”
* Data for Species Assessments
** Using GBIF-mediated data for creating species distribution maps using IUCN mapping standards 
** Using GBIF-mediated data for assessing species conservation status using the IUCN Red List Categories and Criteria 
* Ecological Niche Modelling
** Introduction to running and interpreting a basic ecological model to determine the distribution of a species
** Exploring niche modelling under different environmental conditions



This course is comprised of ... 
Second sentence...
****

=== Audience
This course is for...

=== Prerequisites

To make best use of the activities around this workshop, the participants should possess the following skills and knowledge:

* have a university-level education in biodiversity informatics, ecology or conservation;
* have some understanding of computer-based geographical and statistical analysis tools e.g. GIS and R, and may have already run analyses using these tools;
* have an understanding of national and/or international biodiversity policy e.g. the Convention on Biological Diversity, Sustainable Development Goals, CITES etc;
* have a basic command of English. 
* be able to disseminate the knowledge acquired during the workshop among the rest of the partners of their BID projects.



. prerequisite 1 if any

. prerequisite 2 if any

=== Learning objectives

* Understanding data quality issues that may affect data use and how to handle these data quality issues
* Discern between IUCN mapping protocols and the data requirements of these protocols 
* Apply criterion B of the IUCN Categories and Criteria for the assessment of a species conservation status using a fit-for purpose dataset
* Explain difference between fundamental and realized niches
* Explain how to delimit a training region
* Generate a simple niche model
* Explain niche model results
* Identify areas of uncertainty in projection
* Develop a biodiversity data mainstreaming strategy that considers the national context
* Identify policy entry points and categorize key stakeholders with respect to their relative influence 
* Develop a communication strategy and convincing arguments for the integration of biodiversity into decision making processes


* Objective
* Objective
* Objective
* Objective

// inlude if needed, otherwise remove
=== Certification

Upon successful completion of the course and successful assessment of assignments (by trainers/mentors), participants have the opportunity to receive an official certification in the form of a Mozilla Open Badge.

Participants are required to submit ... and it is scored against the educational rubrics for the course. 

* An overall score of ??? earns a BASIC badge
* An overall score of ??? earns an ADVANCED badge
