[multipage-level=2]
= Use Case 2 - IUCN Red List Assessments

Use Case I is a practice use case for the data proecessing and ecological niche modelling modules. It is recommended that you download the exercise sheet (MS Word 345 KB) so that you can make notes as you work through the exercises. A suggested solution will be provided in the solution appendix. Use Case I is not graded.

Scenario
Mexico is a mega-diverse country with high numbers of species and high levels of endemism across all taxonomic groups.
The government is committed to assessing the conservation status of all its species and has agreed to develop a national red list applying IUCN Categories and Criteria to all vertebrate and invertebrate taxonomic groups by the year 2030. 
As part of this process, they have started the assessment of arachnid groups and are now assessing the conservation status of all species within the family Theraposidae – the tarantulas.  

National and international arachnid specialists have come together at Mexican arachnid red list workshop and they will now be assessing the conservation status of the tarantula species Brachypelma smithi (F.O.Pickard-Cambridge, 1897) and Aphonopelma anax (Chamberlin, 1940).  
Assessors want to use GBIF-mediated data to assess the species using Criterion B and provide maps that comply to IUCN documentation requirements. 

Description
_Brachypelma smithi_ (F.O.Pickard-Cambridge, 1897) is a large spider species in the family Theraphosidae.  
It has a very restricted range within the state of Guerrero, requiring clearings in tropical dry forests on sandy soil where it can build its tunnel/den.  
As with other tarantula species, males and females have different lifespans with averages of 6 and 25 years respectively.  
Both males and females reach sexual maturity on average after 4 years.  
The species plays a role in local indigenous culture where it is considered a vessel for the souls of community members and is thus afforded protection where the species is found near local, indigenous communities.  
The species is threatened by the collection of individuals for the pet trade and is listed under CITES Appendix II; it is highly prized by collectors due to its rarity.  

_Aphonopelma anax_ (Chamberlin, 1940) ) is a large spider species in the family Theraphosidae. 
It is found in Southern Texas, USA and North Mexico. 
They are found in semiarid climates in grasslands and shrub forests as well as within cities. 
They live in burrows that can be created by themselves or modifying suitable habitats such as dead trees, empty rodent burrows, stacks of wood or natural crevices. 
They have slow growth rates and live for several years before maturing – females can live up to 40 years while males rarely live over 2 years once they have matured. 
The species is common across its range and although there has been increasing urban and agricultural development across its range in both the USA and Mexico, the extent of this development is limited to only a small portion of the species entire range.

=== Exercise 1 - Data Processing 

Q1.  What are the taxonkeys for each of the species and what is the taxonomic status of each species?

Q2.  In what format did you download the data and how what are the unique properties of this type of download?

Q3.  What are the DOIs of your downloads?

Q4. What are the following key data quality processing steps did you use for cleaning both datasets?  For each requirement, what is your justification?

* Default geospatial issues
* Absence records
* Fossils and living specimens
* Establishment Means
* Old records
* Uncertain location 
* Bad default values for coordinate uncertainty
* Points along the Equator or prime meridian
* Country centroids
* Duplicate removal
* Outliers
* Metagenomics
* Outside Native ranges
* Gridded datasets
* Automated identifications

Q5. What additional data processing steps might you want to validate taxonomic identification of species?

Q6. As these will be national red list assessments, what additional data processing step will be required for the non-endemic Aphonopelma anax dataset?

=== Exercise 2 - Applying IUCN Red List Criterion B
In this exercise, you will calculate the Extent of Occurrence and Area of Occupancy for Brachypelma smithi using GeoCat - www.geocat.kew.org  and then do a red list assessment for each species based on the information provided in “Data Collection” above. 

[cols="1,1,1"]
|===
3+|_Brachypelma smithi_ (F.O.Pickard-Cambridge, 1897)

|Extent of occurrence
2+|

|Area of Occupancy
2+|

2+|
|Justification (please state whether this is observed, estimated, projected, inferred or suspected)

|Severe Fragmentation 
|Yes or No
|

|Number of Locations 
|
|

|Continuing Decline
|Yes or No
|

|Extreme Fluctuations
|Yes or No
|

|Final Assessment
2+|
|===
[cols="1,1,1"]

|===
3+|_Aphonopelma anax_ (Chamberlin, 1940)

|Extent of occurrence
2+|

|Area of Occupancy
2+|

2+|
|Justification (please state whether this is observed, estimated, projected, inferred or suspected)

|Severe Fragmentation 
|Yes or No
|

|Number of Locations 
|
|

|Continuing Decline
|Yes or No
|

|Extreme Fluctuations
|Yes or No
|

|Final Assessment
2+|
|===

=== Exercise 3 - Producing a Species Distribution Map

In this exercise, you will create a species distribution map for Brachypelma smithi applying IUCN mapping standards.    Please use the step-by-step guide for use case 1 to guide you through this exercise. For assessments that are accompanied by points only, it is recommended, if possible and appropriate, that a polygon map representing the distribution is also provided. Plausible options include, for example, the Minimum Convex Polygon (MCP) map (equivalent to the maximum EOO as defined in this document). Such a polygon should be marked in the polygon attribute table as generalisd = 1 (See Table 3 in Section 4.1.2). It would be used for display on the IUCN Red List website along with the points, and could also be used for analysis purposes.

Q1. Provide the point attributes table in line with IUCN mapping standards for Brachypelma smithi including core, recommended and optional fields for the species distribution map using the processed GBIF data download for this species


Q2. Using the Nature Conservancy Terrestrial Ecosystems dataset provided, what might be appropriate ecosystems to base a polygon map of the limits of a taxon´s distribution for both species?


Q3. If these were freshwater species, what would be an appropriate GIS layer to use for creating polygon maps?


Q4. Provide a polygon map for each of the species.


Q5. What would be appropriate citations for the use of these data?

